apiVersion : apps/v1
kind: Deployment
metadata:
  name: "ctseassignment3-7a1c"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "ctseassignment3-7a1c"
  template:
    metadata:
      labels:
        app: "ctseassignment3-7a1c"
    spec:
      containers:
        - name: "ctseassignment3-7a1c"
          image: "kalanarathnayake.azurecr.io/ctseassignment3"
          ports:
          - containerPort: 8082