apiVersion: v1
kind: Service
metadata:
    name: "ctseassignment3-7a1c"
    labels:
        app: "ctseassignment3-7a1c"
spec:
    type: LoadBalancer
    ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
      name: http
    selector:
        app: "ctseassignment3-7a1c"